#! /bin/sh

PREREQ=""
DESCRIPTION="Disabling unnecessary KDE services..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

rm -f /root/usr/share/autostart/kab2kabc.desktop
rm -f /root/usr/share/autostart/kaddressbookmigrator.desktop
rm -f /root/usr/share/autostart/korgac.desktop
rm -f /root/usr/share/autostart/printer-applet.desktop
rm -f /root/usr/share/autostart/nepomukserver.desktop
rm -f /root/usr/share/kde4/services/kded/kpackagekitd.desktop
if [ -z "${PERSISTENT}" ]; then
	rm -f /root/usr/share/kde4/services/kded/freespacenotifier.desktop
fi
rm -f /root/usr/share/kde4/services/plasma-runner-contacts.desktop  # starts akonadi
rm -f /root/usr/share/kde4/services/plasma-dataengine-calendar.desktop  # starts akonadi

for pkg in kubuntu-default-settings ubuntustudio; do
	settingsdir="/root/usr/share/$pkg/kf5-settings"
	[ -d "$settingsdir" ] || continue
	printf "[Daemon]\nTimeout=0\nAutolock=false\n" >> "$settingsdir"/kscreenlockerrc
	printf "[Basic Settings]\nIndexing-Enabled=false\n" >> "$settingsdir"/baloofilerc
	printf "[Module-notificationhelper]\nautoload=false\n" >> "$settingsdir"/kded5rc
	printf "[Event/Update]\nAction=\n" >> "$settingsdir"/muonabstractnotifier.notifyrc
	printf "[Event/Update]\nAction=\n" >> "$settingsdir"/muonapplicationnotifier.notifyrc
	printf "[Wallet]\nEnabled=false\n" >> "$settingsdir"/kwalletrc
done

log_end_msg
